import React from "react";

// export function Hello(){
    //return <h1>Hello,I am coming via jsx</h1>;

    // return(
    //     <div id="conatiner">

    //       <h1 id="container">
    //            Hello i am inisde a div using jsx.
    //       </h1>
        
    //     </div>
    // )

    // return <h1>Hello</h1>;


    //  }

     const App =() => <h1>hello</h1>;
     export default App;







//export default Hello;

